ERROR 2025-08-01 12:44:18,934 log Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/middleware/security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
ERROR 2025-08-01 12:44:19,073 log Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/middleware/security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
ERROR 2025-08-01 12:44:37,451 log Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/middleware/security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
ERROR 2025-08-01 12:44:37,478 log Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/middleware/security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
                                 ~~~~~~~~~~~~~~~~^^
  File "/Users/petergangmei/Developer/Crossplatform/django/northeastindia_wiki/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
